In [1]:
import pandas as pd
import sklearn
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm

In [44]:
#data=pd.read_csv('mlinput.csv')
data=pd.read_csv('onlylabel.csv')

In [45]:
data.head()

Applications Sentiment      Emotions  ability  able  about  above  absolute  \
0        Boost  Negative         Anger      0.0   0.0    0.0    0.0       0.0   
1        Boost  Negative         Anger      0.0   0.0    0.0    0.0       0.0   
2        Boost  Positive           Joy      0.0   0.0    0.0    0.0       0.0   
3        Boost  Negative         Anger      0.0   0.0    0.0    0.0       0.0   
4        Boost  Positive  Anticipation      0.0   0.0    0.0    0.0       0.0   

   absolutely  accept  ...   years  yes  yesterday       yet   yo       you  \
0         0.0     0.0  ...     0.0  0.0        0.0  0.000000  0.0  0.000000   
1         0.0     0.0  ...     0.0  0.0        0.0  0.155634  0.0  0.000000   
2         0.0     0.0  ...     0.0  0.0        0.0  0.000000  0.0  0.160866   
3         0.0     0.0  ...     0.0  0.0        0.0  0.000000  0.0  0.000000   
4         0.0     0.0  ...     0.0  0.0        0.0  0.000000  0.0  0.000000   

   your  yourself   yr  zero  
0   0.0       0.0  0.0   0.0  
1   0.0       0.0  0.0   0.0  
2   0.0       0.0  0.0   0.0  
3   0.0       0.0  0.0   0.0  
4   0.0       0.0  0.0   0.0  

[5 rows x 1733 columns]

In [6]:
#change sentiment to 0,1,2 
#data.loc[data["Sentiment"]=='Neutral',"Sentiment",]=0
#data.loc[data["Sentiment"]=='Positive',"Sentiment",]=1
#data.loc[data["Sentiment"]=='Negative',"Sentiment",]=2
#data.head()

Applications  Sentiment Emotions   aa  abandon  ability  able  about  above  \
0        Boost          2        1  0.0      0.0      0.0   0.0    0.0    0.0   
1          TNG          2        1  0.0      0.0      0.0   0.0    0.0    0.0   
2      Maybank          1        0  0.0      0.0      0.0   0.0    0.0    0.0   
3        Boost          2        1  0.0      0.0      0.0   0.0    0.0    0.0   
4          TNG          2        2  0.0      0.0      0.0   0.0    0.0    0.0   

   absolute  ...        yet  yew   yo  you  young  your  yourself  youve   yr  \
0       0.0  ...   0.000000  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   
1       0.0  ...   0.000000  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   
2       0.0  ...   0.000000  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   
3       0.0  ...   0.160757  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   
4       0.0  ...   0.000000  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   

   zero  
0   0.0  
1   0.0  
2   0.0  
3   0.0  
4   0.0  

[5 rows x 2785 columns]

In [7]:
#change emotion to 1,2,3,4,5,6,7,8
#data.loc[data["Emotions"]=='Joy',"Emotions",]=0
#data.loc[data["Emotions"]=='Anger',"Emotions",]=1
#data.loc[data["Emotions"]=='Anticipation',"Emotions",]=2
#data.loc[data["Emotions"]=='Disgust',"Emotions",]=3
#data.loc[data["Emotions"]=='Fear',"Emotions",]=4
#data.loc[data["Emotions"]=='Surprise',"Emotions",]=5
#data.loc[data["Emotions"]=='Sadness',"Emotions",]=6
#data.loc[data["Emotions"]=='Trust',"Emotions",]=7
#data.loc[data["Emotions"]=='Neutral',"Emotions",]=8
#data.head()

Applications  Sentiment Emotions   aa  abandon  ability  able  about  above  \
0        Boost          2        1  0.0      0.0      0.0   0.0    0.0    0.0   
1          TNG          2        1  0.0      0.0      0.0   0.0    0.0    0.0   
2      Maybank          1        0  0.0      0.0      0.0   0.0    0.0    0.0   
3        Boost          2        1  0.0      0.0      0.0   0.0    0.0    0.0   
4          TNG          2        2  0.0      0.0      0.0   0.0    0.0    0.0   

   absolute  ...        yet  yew   yo  you  young  your  yourself  youve   yr  \
0       0.0  ...   0.000000  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   
1       0.0  ...   0.000000  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   
2       0.0  ...   0.000000  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   
3       0.0  ...   0.160757  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   
4       0.0  ...   0.000000  0.0  0.0  0.0    0.0   0.0       0.0    0.0  0.0   

   zero  
0   0.0  
1   0.0  
2   0.0  
3   0.0  
4   0.0  

[5 rows x 2785 columns]

In [46]:
#filter only sentiment for sentiment analysis

#filter out neutral sentiment and only emotion for emotion analysis
X = data.iloc[:, 3:1734]
y = data.iloc[:, 1]

In [47]:
#Xe do not need sentiment=neutral 
#drop fear and disgust as well
Xe=data[(data['Emotions']!='Neutral')&(data['Emotions']!='Fear')&(data['Emotions']!='Disgust')].iloc[:,3:1734]

In [48]:
#ye is just emotion rows without neutral/8, no others
#drop fear and disgust as well
#make sure the output is recognized as multiclass
ye=data[(data['Emotions']!='Neutral')&(data['Emotions']!='Fear')&(data['Emotions']!='Disgust')].iloc[:,2]

In [8]:
#10 fold cross validation, no need train/test split due to cross-validation
#first reference
from sklearn.model_selection import StratifiedKFold
k_fold = StratifiedKFold(n_splits=10, shuffle=True, random_state=123)

In [30]:
from imblearn.over_sampling import SMOTE
sm=SMOTE()
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [34]:
from sklearn import tree
clf_dt = tree.DecisionTreeClassifier(random_state=123,criterion='entropy')
from sklearn.naive_bayes import MultinomialNB
clf_nb = MultinomialNB(alpha=1.0, fit_prior=True, class_prior=None)
from sklearn.svm import SVC
clf_svm = SVC(C=1.0,kernel='linear',random_state=123)
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
clf_rfb = BaggingClassifier(base_estimator=tree.DecisionTreeClassifier(random_state=123,criterion='entropy'),n_estimators=100,random_state=123)
clf_rf = RandomForestClassifier(n_estimators=100,random_state=123,bootstrap=True,criterion='entropy')

In [52]:
#SMOTE on training set only for Sentiment Analysis
#for cross validation one, apply looping to run SMOTE on each traning set chosen in each iteration
#perform oversampling during cross-validation, 
#i.e. for each fold, oversampling is performed before training, 
#and this process is repeated for each fold.
for (train_index, test_index) in k_fold.split(X, y):
    X_train = X.iloc[train_index]
    y_train = y.iloc[train_index]
    X_test = X.iloc[test_index]
    y_test = y.iloc[test_index]
    X_train_oversampled, y_train_oversampled = sm.fit_sample(X_train, y_train)

Accuracy=0.7289719626168224
F1=0.6804094055231537
Kappa=0.4854063018242122
CM=[[53  1  5]
 [14  0  1]
 [ 7  1 25]]
Accuracy=0.7757009345794392
F1=0.7221750212404416
Kappa=0.574693607154687
CM=[[54  1  4]
 [15  0  0]
 [ 4  0 29]]
Accuracy=0.7904761904761904
F1=0.7294074881861141
Kappa=0.5994451187792613
CM=[[56  0  2]
 [12  0  3]
 [ 5  0 27]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.7523809523809524
F1=0.6942573825869021
Kappa=0.5111906893464637
CM=[[56  0  2]
 [15  0  0]
 [ 9  0 23]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.7619047619047619
F1=0.7035897435897436
Kappa=0.546866908337649
CM=[[53  0  5]
 [14  0  1]
 [ 5  0 27]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.7619047619047619
F1=0.7083609840671988
Kappa=0.5378521126760563
CM=[[55  1  2]
 [15  0  0]
 [ 7  0 25]]
Accuracy=0.7428571428571429
F1=0.6889249639249639
Kappa=0.5163766632548619
CM=[[52  1  5]
 [12  0  3]
 [ 6  0 26]]
Accuracy=0.7142857142857143
F1=0.6627845273006563
Kappa=0.4529350468912816
CM=[[51  1  6]
 [15  0  0]
 [ 8  0 24]]
Accuracy=0.7523809523809524
F1=0.6985142487868768
Kappa=0.5280082987551866
CM=[[53  1  4]
 [14  0  1]
 [ 6  0 26]]
Accuracy=0.780952380952381
F1=0.7212510200930766
Kappa=0.5886561062851303
CM=[[52  0  6]
 [15  0  0]
 [ 2  0 30]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
#Decision Tree
#clf_dt.fit(X_train_oversampled,y_train_oversampled)
#ypred=clf_dt.predict(X_test)

#Naive Bayes
#clf_nb.fit(X_train_oversampled,y_train_oversampled)
#ypred=clf_nb.predict(X_test)

#SVM
#clf_svm.fit(X_train_oversampled,y_train_oversampled)
#ypred=clf_svm.predict(X_test)

#Bagging
#clf_rfb.fit(X_train_oversampled,y_train_oversampled)#ypred=clf_rfb.predict(X_test)

#Random Forest
#clf_rf.fit(X_train_oversampled,y_train_oversampled)
#ypred=clf_rf.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, ypred)
print("Accuracy="+str(accuracy))
f1score=f1_score(y_test,ypred,average='weighted')
print("F1="+str(f1score))
kappa_score=cohen_kappa_score(y_test,ypred)
print("Kappa="+str(kappa_score))
cm=confusion_matrix(y_test,ypred)
print("CM="+str(cm))

In [56]:
#Emotion Analysis
for (train_index, test_index) in k_fold.split(Xe, ye):
    Xe_train = Xe.iloc[train_index]
    ye_train = ye.iloc[train_index]
    Xe_test = Xe.iloc[test_index]
    ye_test = ye.iloc[test_index]
    Xe_train_oversampled, ye_train_oversampled = sm.fit_sample(Xe_train, ye_train)

Accuracy=0.6451612903225806
F1=0.5796500105418512
Kappa=0.4400656814449918
CM=[[38  3  1  0  0  0]
 [ 7  6  3  0  0  0]
 [ 5  0 16  0  0  0]
 [ 6  0  2  0  0  0]
 [ 2  0  0  0  0  0]
 [ 2  0  2  0  0  0]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.5934065934065934
F1=0.5197912455437539
Kappa=0.3460866187609244
CM=[[38  2  1  1  0  0]
 [12  2  1  0  0  0]
 [ 3  3 14  0  0  0]
 [ 6  0  2  0  0  0]
 [ 1  1  0  0  0  0]
 [ 2  0  2  0  0  0]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.6444444444444445
F1=0.5874774774774775
Kappa=0.42423030787684934
CM=[[39  2  1  0  0  0]
 [ 6  7  2  0  0  0]
 [ 7  0 12  0  0  1]
 [ 7  1  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 2  0  2  0  0  0]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.6666666666666666
F1=0.6059777983481512
Kappa=0.46097025354362153
CM=[[41  1  0  0  0  0]
 [ 6  5  4  0  0  0]
 [ 7  0 13  0  0  0]
 [ 5  1  2  0  0  0]
 [ 1  0  0  0  0  0]
 [ 1  0  2  0  0  1]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.6222222222222222
F1=0.5495594552198326
Kappa=0.3789324132332047
CM=[[40  1  1  0  0  0]
 [10  4  1  0  0  0]
 [ 8  0 12  0  0  0]
 [ 4  2  2  0  0  0]
 [ 1  0  0  0  0  0]
 [ 1  0  3  0  0  0]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.6111111111111112
F1=0.5493282337942531
Kappa=0.37313432835820903
CM=[[40  1  1  0  0  0]
 [ 7  5  2  0  0  1]
 [ 8  1 10  0  0  1]
 [ 5  0  3  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  4  0  0  0]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.6067415730337079
F1=0.5323962245528733
Kappa=0.3549389107475668
CM=[[40  1  1  0  0  0]
 [ 8  3  4  0  0  0]
 [ 7  2 11  0  0  0]
 [ 5  0  2  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  4  0  0  0]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.6436781609195402
F1=0.569893763783661
Kappa=0.3951558645436196
CM=[[41  0  0  0  0  0]
 [10  3  2  0  0  0]
 [ 6  1 12  0  0  1]
 [ 6  0  1  0  0  0]
 [ 1  0  0  0  0  0]
 [ 3  0  0  0  0  0]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.5862068965517241
F1=0.5212814384886765
Kappa=0.3226643598615917
CM=[[38  0  3  0  0  0]
 [ 9  3  3  0  0  0]
 [ 7  1 10  1  0  1]
 [ 5  1  1  0  0  0]
 [ 1  0  0  0  0  0]
 [ 0  0  3  0  0  0]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Accuracy=0.6091954022988506
F1=0.5354342188051503
Kappa=0.34046822742474914
CM=[[40  1  0  0  0  0]
 [ 8  3  3  0  0  1]
 [ 9  1 10  0  0  0]
 [ 7  0  0  0  0  0]
 [ 1  0  0  0  0  0]
 [ 1  0  2  0  0  0]]


C:\Users\loel7003\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
#Decision Tree
#clf_dt.fit(Xe_train_oversampled,ye_train_oversampled)
#yepred=clf_dt.predict(Xe_test)

#Naive Bayes
#clf_nb.fit(Xe_train_oversampled,ye_train_oversampled)
#yepred=clf_nb.predict(Xe_test)

#SVM
#clf_svm.fit(Xe_train_oversampled,ye_train_oversampled)
#yepred=clf_svm.predict(Xe_test)

#Bagging
#clf_rfb.fit(Xe_train_oversampled,ye_train_oversampled)
#yepred=clf_rfb.predict(Xe_test)

#Random Forest
#clf_rf.fit(Xe_train_oversampled,ye_train_oversampled)
#yepred=clf_rf.predict(Xe_test)

In [ ]:
accuracy = accuracy_score(ye_test, yepred)
print("Accuracy="+str(accuracy))
f1score=f1_score(ye_test,yepred,average='weighted')
print("F1="+str(f1score))
kappa_score=cohen_kappa_score(ye_test,yepred)
print("Kappa="+str(kappa_score))
cm=confusion_matrix(ye_test,yepred)
print("CM="+str(cm))